UserManagementApp/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserManagementApp.Data;
using UserManagementApp.Models;

namespace UserManagementApp.Controllers
{
    public class PermissionsController : Controller
    {
        private UserManagementAppContext db = new UserManagementAppContext();
        private static int userID;

        // GET: Permissions
        
        public ActionResult Index(int? id)
        {
            if(id != null) userID = (int)id;

            var permissions = db.PermissionModels.ToList().FindAll(x => x.UserModelID_FK == userID);
            if (permissions == null) permissions = new List<PermissionModel>();
            return View(permissions);
        }

        // GET: Permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PermissionModel permissionModel = db.PermissionModels.Find(id);
            if (permissionModel == null)
            {
                return HttpNotFound();
            }
            return View(permissionModel);
        }

        // GET: Permissions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Permissions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Code,Description,UserModelID_FK")] PermissionModel permissionModel)
        {
            if (ModelState.IsValid)
            {
                permissionModel.UserModelID_FK = userID;
                db.PermissionModels.Add(permissionModel);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = userID });
            }

            return View(permissionModel);
        }

        // GET: Permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PermissionModel permissionModel = db.PermissionModels.Find(id);
            if (permissionModel == null)
            {
                return HttpNotFound();
            }
            return View(permissionModel);
        }

        // POST: Permissions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Code,Description,UserModelID_FK")] PermissionModel permissionModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permissionModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permissionModel);
        }

        // GET: Permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PermissionModel permissionModel = db.PermissionModels.Find(id);
            if (permissionModel == null)
            {
                return HttpNotFound();
            }
            return View(permissionModel);
        }

        // POST: Permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PermissionModel permissionModel = db.PermissionModels.Find(id);
            db.PermissionModels.Remove(permissionModel);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = userID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserManagementApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using UserManagementApp.Data;
using UserManagementApp.Models;

namespace UserManagementApp.Controllers
{
    public class UsersController : Controller
    {
        private UserManagementAppContext db = new UserManagementAppContext();
        private const int pageSize = 10;

        // GET: Users
        public ActionResult Index(int page = 0, string sortOrder = "", string sortParameter = "", string searchString = "")
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["SortOrder"] = sortOrder;
            ViewData["SortParameter"] = sortParameter;

         //   var count = db.UserModels.Count();
            var data = from u in db.UserModels select u;

            if (!String.IsNullOrEmpty(searchString))
            {
                data = data.Where(u => u.LastName.Contains(searchString) || u.FirstName.Contains(searchString));
            }

            data = UserManagementApp.Helpers.Sorting.SortUsersData(data, sortParameter, sortOrder);

            var count = data.Count();
            var dataForPage = data.Skip(page * pageSize).Take(pageSize).ToList();            

            ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
            ViewBag.Page = page;

            return View(dataForPage);
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserModel userModel = db.UserModels.Find(id);
            if (userModel == null)
            {
                return HttpNotFound();
            }
            return View(userModel);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Username,Password,Email,Status")] UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                db.UserModels.Add(userModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userModel);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserModel userModel = db.UserModels.Find(id);
            if (userModel == null)
            {
                return HttpNotFound();
            }
            return View(userModel);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserModel userModel)
        {
            var userInDB = db.UserModels.ToList().Find(x => x.ID == userModel.ID);
            userInDB.FirstName = userModel.FirstName;
            userInDB.LastName = userModel.LastName;
            userInDB.Email = userModel.Email;
            userInDB.Status = userModel.Status;

            db.Entry(userInDB).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");    
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserModel userModel = db.UserModels.Find(id);
            if (userModel == null)
            {
                return HttpNotFound();
            }
            
            return View(userModel);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserModel userModel = db.UserModels.Find(id);
            db.UserModels.Remove(userModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

       
    }
}

UserManagementApp/Views/Permissions/Create.cshtml
@model UserManagementApp.Models.PermissionModel

@{
    ViewBag.Title = "Create permission";
}

<h2>Create new permission for the user</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Permissions")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UserManagementApp/Views/Permissions/Delete.cshtml
@model UserManagementApp.Models.PermissionModel

@{
    ViewBag.Title = "Delete permission";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
     
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UserManagementApp/Views/Permissions/Index.cshtml
@model IEnumerable<UserManagementApp.Models.PermissionModel>

@{
    ViewBag.Title = "Permissions";
}

<h2>Permissions</h2>

<p>
    @Html.ActionLink("Add new permission", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Remove", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.ActionLink("Back to users", "Index", "Users")
    </div>
}